### ISSUE TITLE
Cannot open INAV blackbox log

### ISSUE THREAD

**Issue by avsaase** [bw1129/PIDtoolbox#65]
I am not able to open the attached INAV blackbox log using 0.44:
![image](https://user-images.githubusercontent.com/880421/129602046-14983f26-ac50-4db0-9c4f-833008d4eb5c.png)

The file opens just fine in INAV Blackbox Explorer 3.4.0  and decodes without issues (0.1% dropped frames) with INAV's `blackbox_decode` 0.4.6.

The logging frequency is ~250Hz (2KHz loop frequency and 1/8 logging rate). I am aware this is probably not enough to make use of all features of PIDtoolbox but I figured it should be able to open the file.

[LOG017.TXT](https://github.com/bw1129/PIDtoolbox/files/6994142/LOG017.TXT)

**Comment by bw1129** [comment]
Make sure blackbox_decode_INAV is in folder with the logfiles. Log rate 1k minimum.

**Comment by avsaase** [comment]
Yes, I have `blackbox_decode_INAV` in the same folder as the log file. 

Can you confirm it is the logging rate that causes this? I think in principle it should be possible to do some step response analysis at 250Hz. Probably not ideal but I can't go higher with a serial logger because INAV logs a lot of variables and does not currently support selecting which variables are logged.

**Comment by bw1129** [comment]
no issue loading it here. just wont work on the tools at 250hz. crashes in both spec analyzer and step resp when trying to plot
![PTB_FIGS_LOG017xx_16-Aug-2021-1](https://user-images.githubusercontent.com/17284912/129614766-d873e8b8-b1ef-4754-8924-a008a6b38d4e.png)

**Comment by bw1129** [comment]
ok, managed to get it running. I can fix this. maybe I could upload a new version to github. I'll just replace v0.44 with this
![PTB_FIGS_LOG017xx_16-Aug-2021-2](https://user-images.githubusercontent.com/17284912/129617120-16c21fe1-1f2e-404e-a58f-3846f7e5f1af.png)

**Comment by avsaase** [comment]
That would be awesome. Thanks! And how about the spectrum analyzer? Blackbox explorer shows the spectrum up to half the logging rate. Even at 250Hz, this could provide some useful information.

I had some problems updating to 0.44. Maybe that caused my import problem. I'll try removing and reinstalling.

Again, thanks a lot!

**Comment by bw1129** [comment]
yes, spec still works. just only goes to 125Hz (because of nyquist limit!)

**Comment by bw1129** [comment]
@avsaase I made that edit on the win version so it should work now with logs < 1k. I didnt issue it as new release because it was so minor, so just download the latest executable and replace with the one you have now. I'll do same for mac and linux in a minute

**Comment by avsaase** [comment]
Do you know what could the error I posted in the OP? I replaced the executable (and the other files) with the updated 0.44 Windows version but I still get the same error. I have Matlab installed on my system. Could that have something to do with it?

**Comment by bw1129** [comment]
Double confirm blackbox_decode_INAV is in there. Make sure there is write access to folder. It could be read only.

**Comment by bw1129** [comment]
Also make sure logfiledir.txt is in pidtoolbox main folder. This is a file that records and holds previous selected folder location so when you reselect it redirects you to that folder. If all that doesn’t work drop the file right there in main folder and see if that works as a test.

**Comment by avsaase** [comment]
> If all that doesn’t work drop the file right there in main folder and see if that works as a test.

Okay, this works. Before, the LOG file was in a folder with write access, along with blackbox_decode_INAV.exe. I checked if it was because the LOG file was on a different drive than the PIDtoolbox executable but that was not the problem.

**Comment by bw1129** [comment]
Ok so you have a solution. Not an ideal solution, but a solution nonetheless.

**Comment by avsaase** [comment]
That's true. Thanks a lot for helping me out. I understand you don't want to do a new release right now, but I think more people could benefit from blackbox analysis at lower logging rates.

**Comment by bw1129** [comment]
Yes the step tool for sure! I’m impressed it worked so well. That’s promising

**Comment by bw1129** [comment]
@avsaase I injected a small bug in the program doing this. I ave to revert for now and try to solve it correctly. It's ok for your purpose for now, but I need to fix this

**Comment by avsaase** [comment]
Sure, no problem. I have a working executable now.

Regarding my error opening log, if I open the first log by first placing it in the same folder as PIDtoolbox, then subsequent logs can be opened from any folder.

**Comment by avsaase** [comment]
Will the ability to open <1kHz logs be part of the next release? If so then this issue can be closed.

**Comment by bw1129** [comment]
Yes. It’ll be in next release. Thx

**Comment by avsaase** [comment]
This is technically a new feature request but it would be great if PIDtoolbox could import decoded CSV logs. 

Right now, with logs that contain multiple flights, you need to decode the log from PIDtoolbox, select which flight you want (after which it deletes the decoded CSV files) and repeat for the other flights from the same file.

**Comment by bw1129** [comment]
PTB does import decoded csv files technically but I think I understand your request. Others have asked same. I’ve been thinking about how to do this as it’s a bit tricky but should have a solution soon

**Comment by avsaase** [comment]
The option to import multiple flights from the same file in one go, with an indication of which log is which flight, would achieve the same thing for me.
